### ISSUE TITLE
priviliges code breaks on tables with no priviliges

### ISSUE THREAD

**Issue by reedstrm** [perseas/Pyrseas#125]
If all privs have been REVOKED, we get a traceback:

```
psql test -c 'create table test (t text); revoke all on test from public; revoke all on test from reedstrm'

dbtoyaml test

Traceback (most recent call last):
  File "/home/reedstrm/src/db-versioning/bin/dbtoyaml", line 9, in <module>
    load_entry_point('Pyrseas==0.7.2', 'console_scripts', 'dbtoyaml')()
  File "/home/reedstrm/src/db-versioning/Pyrseas/pyrseas/dbtoyaml.py", line 49, in main
    dbmap = db.to_map()
  File "/home/reedstrm/src/db-versioning/Pyrseas/pyrseas/database.py", line 314, in to_map
    dbmap.update(self.db.schemas.to_map(opts))
  File "/home/reedstrm/src/db-versioning/Pyrseas/pyrseas/dbobject/schema.py", line 327, in to_map
    schemas.update(self[sch].to_map(self, opts))
  File "/home/reedstrm/src/db-versioning/Pyrseas/pyrseas/dbobject/schema.py", line 63, in to_map
    schobjs.append((obj, obj.to_map(dbschemas, opts)))
  File "/home/reedstrm/src/db-versioning/Pyrseas/pyrseas/dbobject/table.py", line 298, in to_map
    tbl.update({'privileges': self.map_privs()})
  File "/home/reedstrm/src/db-versioning/Pyrseas/pyrseas/dbobject/__init__.py", line 305, in map_privs
    privlist.append(privileges_to_map(prv, self.allprivs, self.owner))
  File "/home/reedstrm/src/db-versioning/Pyrseas/pyrseas/dbobject/privileges.py", line 66, in privileges_to_map
    (usr, privcodes, grantor) = _split_privs(privspec)
  File "/home/reedstrm/src/db-versioning/Pyrseas/pyrseas/dbobject/privileges.py", line 21, in _split_privs
    (usr, prvgrant) = privspec.split('=')
ValueError: need more than 1 value to unpack
```

**Comment by jmafc** [comment]
This appears to be a regression introduced by some recent change because the problem doesn't occur in the head of branch r0.7 (which is essentially 0.7.2 + fixes for issues 112 and 114).  The most likely culprit is 5da6b0c.

**Comment by jmafc** [comment]
Confirmed. The problem occurs in the master branch with change 5da6b0c but does not occur with change e3afcd7. You can either use 0.7.2, or the head of branch r0.7, or if you must use master do a `git checkout e3afcd7` (at least until I can take a closer look and fix it).

**Comment by reedstrm** [comment]
Thanks for the quick fix. My workaround here was just to add some privs to the table, but a proper fix is always best.
