### ISSUE TITLE
dbtoyaml 0.7.1 crashes on sequences it's not supposed to dump

### ISSUE THREAD

**Issue by dvarrazzo** [perseas/Pyrseas#99]
If there is a table the user running pyrseas can't read, and it contains a sequence:

```
$ psql -U postgres pyrseas
pyrseas=# create schema forbidden;
pyrseas=# create table forbidden.test (id serial);
```

and pyrseas run with a different user, it will crash even if it's not requested to dump that schema:

```
$ dbtoyaml -n public -U piro pyrseas  # user piro can't read the `forbidden.test` table

Traceback (most recent call last):
  File "/usr/local/bin/dbtoyaml", line 9, in <module>
    load_entry_point('Pyrseas==0.7.1', 'console_scripts', 'dbtoyaml')()
  File "/usr/local/lib/python2.7/dist-packages/pyrseas/dbtoyaml.py", line 49, in main
    dbmap = db.to_map()
  File "/usr/local/lib/python2.7/dist-packages/pyrseas/database.py", line 263, in to_map
    self.from_catalog()
  File "/usr/local/lib/python2.7/dist-packages/pyrseas/database.py", line 170, in from_catalog
    self.db = self.Dicts(self.dbconn)
  File "/usr/local/lib/python2.7/dist-packages/pyrseas/database.py", line 92, in __init__
    self.tables = ClassDict(dbconn)
  File "/usr/local/lib/python2.7/dist-packages/pyrseas/dbobject/__init__.py", line 471, in __init__
    self._from_catalog()
  File "/usr/local/lib/python2.7/dist-packages/pyrseas/dbobject/table.py", line 668, in _from_catalog
    inst.get_attrs(self.dbconn)
  File "/usr/local/lib/python2.7/dist-packages/pyrseas/dbobject/table.py", line 48, in get_attrs
    FROM %s.%s""" % (quote_id(self.schema), quote_id(self.name)))
  File "/usr/local/lib/python2.7/dist-packages/pyrseas/lib/dbconn.py", line 93, in fetchone
    curs = self.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/pyrseas/lib/dbconn.py", line 81, in execute
    raise exc
psycopg2.ProgrammingError: permission denied for relation test_id_seq
```

The same excluding the schema with `-N forbidden`.

**Comment by jmafc** [comment]
Confirmed this happens against Pyrseas 0.7.3 as well as current master (Pyrseas 0.8.dev0).

**Comment by jmafc** [comment]
@dvarrazzo The problem is that, prior to PG 10, the only way to get the attributes (start value, increment, etc.) of a sequence was by doing a SELECT on the sequence itself (in PG 10, we're now SELECTing from `pg_sequences` so this problem goes away). We know about the sequence because we first query `pg_class`.

It seems that the way to fix this for pre-PG 10 releases would be putting a `try/except` around the SELECT on the sequence and to skip further processing on it (probably remove the sequence from the `ClassDict`).

**Comment by forbesmyester** [comment]
I don't see why would it be looking at that schema anyway? It happens if `forbidden` is not in the search path, there are no tables/anything referencing `forbidden`, you specifically tell it to only dump another schema and specifically not to look in `forbidden`.

**Comment by jmafc** [comment]
@forbesmyester I tried to explain why in my comment above. Let me expand on it. The way `dbtoyaml` operates is by first querying the PG system catalogs for (nearly) all non-system objects. This works regardless of the user and the permissions he or she has because in general the catalog information is publicly visible. We fetch everything first because there can be cross-schema relationships between objects (see the `autodoc` schema for examples). Then in the second phase, we may limit the output based on command line options. The search_path plays no part in any of this since we explicitly set it to `pg_catalog`. Unfortunately, as described previously, before PG 10 we had to query the actual sequence table to get the sequence information.

**Comment by jmafc** [comment]
@dvarrazzo Please read https://pyrseas.wordpress.com/2018/09/12/the-future-of-pyrseas-revisited/ if you have not already done so.
